src/github/github.api.ts
src/github/types/queries.interface.ts

Resolves #15 
Time spent: 1.5d

feat: update total contributions

---

src/contributors/contributor.dto.ts
src/contributors/contributor.entity.ts
src/contributors/contributors.repository.mock.ts
src/github/github.api.mock.ts
src/github/github.api.ts
src/github/metrics/contributed-repository-count.metric.spec.ts
src/github/metrics/contributed-repository-count.metric.ts
src/github/metrics/index.ts
src/github/metrics/query-response.example.json
src/github/types/user.interface.ts

feat: contributed repository count metric

---

src/contributors/contributor.dto.ts
src/contributors/contributor.entity.ts
src/contributors/contributor.factory.ts
src/contributors/contributors.repository.mock.ts
src/github/github.api.mock.ts
src/github/github.api.ts
src/github/metrics/index.ts
src/github/metrics/issue-pull-request-ratio.metric.spec.ts
src/github/metrics/issue-pull-request-ratio.metric.ts
src/github/metrics/query-response.example.json
src/github/types/user.interface.ts
src/scorer/normalization.service.spec.ts
src/scorer/normalization.service.ts

feat: issue pull request ratio metric

---

src/commands/commands.module.ts
src/commands/score-contributors.command.spec.ts
src/commands/score-contributors.command.ts
src/commands/synchronize-contributor.command.spec.ts
src/commands/synchronize-contributor.command.ts
src/contributors/contributor.entity.ts
src/contributors/contributors.repository.mock.ts
src/contributors/contributors.service.spec.ts
src/contributors/contributors.service.ts
src/scorer/index.ts
src/scorer/scorer.module.ts
src/scorer/scorer.service.spec.ts
src/scorer/scorer.service.ts
src/scorer/standard-scaler.service.ts
src/synchronization/synchronization.module.ts
src/synchronization/synchronization.service.spec.ts
src/synchronization/synchronization.service.ts

feat: add scoring command

---

src/contributors/contributor.dto.ts
src/contributors/contributor.entity.ts
src/github/types/user.interface.ts

fix: github user name can be nullable

---

src/scorer/normalization.service.spec.ts

fix: failing normalization tests

---

.github/workflows/release.yml

chore: disable husky for the version creation workflow

---

src/commands/commands.module.ts
src/commands/index.ts
src/commands/onlydust-import.command.spec.ts
src/commands/onlydust-import.command.ts
src/github/metrics/issue-pull-request-ratio/issue-pull-request-ratio.metric.ts
src/onlydust/onlydust.api.ts
src/onlydust/onlydust.module.ts
src/synchronization/synchronization.service.ts

feat: add Onlydust import command

---

README.md
src/commands/onlydust-import.command.ts
src/commands/score-contributors.command.ts
src/commands/synchronize-contributor.command.ts

docs: update readme

---

src/commands/onlydust-import.command.spec.ts
src/commands/onlydust-import.command.ts
src/github/exceptions/index.ts
src/github/exceptions/user-not-found.exception.ts
src/github/github.api.ts
src/github/index.ts

fix: update onlydust import command

---

src/commands/onlydust-import.command.spec.ts
src/commands/score-contributors.command.spec.ts
src/commands/synchronize-contributor.command.spec.ts
src/contributors/contributors.testing-module.ts
src/contributors/index.ts
src/github/github.testing-module.ts
src/github/index.ts
src/metrics/index.ts
src/metrics/metrics.service.spec.ts
src/metrics/metrics.testing-module.ts
src/onlydust/index.ts
src/onlydust/onlydust.testing-module.ts
src/synchronization/index.ts
src/synchronization/synchronization.service.spec.ts
src/synchronization/synchronization.testing-module.ts

test: add testing modules

---

src/onlydust/onlydust.api.ts

fix: onlydust import failing command

---

src/contributors/contributors.controller.spec.ts
src/contributors/contributors.controller.ts
src/contributors/contributors.repository.mock.ts
src/contributors/contributors.service.spec.ts
src/contributors/contributors.service.ts

feat: add an endpoint for reading a contributor by its username

---

src/contributors/contributor.dto.ts
src/contributors/contributor.entity.ts
src/contributors/contributor.factory.spec.ts
src/contributors/contributor.factory.ts
src/metrics/metric-name.ts
src/metrics/metrics.service.spec.ts
src/onlydust/onlydust.api.mock.ts
src/onlydust/onlydust.api.ts
src/onlydust/onlydust.service.spec.ts
src/onlydust/onlydust.service.ts
src/scorer/scorer.service.ts
src/synchronization/synchronization.service.spec.ts

feat: add mean grant per project metric

---

src/contributors/contributor.dto.ts
src/contributors/contributor.entity.ts
src/contributors/contributor.factory.spec.ts
src/contributors/contributor.factory.ts
src/contributors/contributors.controller.spec.ts
src/contributors/contributors.service.spec.ts
src/metrics/metric-name.ts
src/metrics/metrics.service.spec.ts
src/onlydust/onlydust.api.mock.ts
src/onlydust/onlydust.api.ts
src/onlydust/onlydust.service.spec.ts
src/onlydust/onlydust.service.ts
src/scorer/scorer.service.ts
src/synchronization/synchronization.service.spec.ts

feat: add contributed project count metric

---

src/synchronization/synchronization.service.ts

feat: the synchronization command fails past a given number of users

---

src/commands/onlydust-import.command.ts

fix: ignore github bots in onlydust import

---

src/metrics/metrics.service.ts
src/onlydust/onlydust.api.ts

fix: the synchronization command fails to fetch user info in parallel

---

k8s/staging/cronjob.yaml

fix: cron job now synchronizes every user

---

src/contributors/contributors.controller.spec.ts
src/contributors/contributors.controller.ts
src/contributors/contributors.module.ts
src/contributors/contributors.service.spec.ts
src/contributors/contributors.service.ts
src/contributors/contributors.testing-module.ts
src/synchronization/synchronization.module.ts
src/synchronization/synchronization.service.ts
src/synchronization/synchronization.testing-module.ts

feat: add a post endpoint for adding a contributor

---

src/contributors/contributor.factory.ts
src/contributors/contributors.controller.spec.ts
src/contributors/types/contributor.interface.ts
src/metrics/metric-name.ts
src/metrics/metrics.entity.ts
src/metrics/metrics.factory.ts
src/metrics/metrics.service.spec.ts
src/onlydust/onlydust.api.mock.ts
src/onlydust/onlydust.api.ts
src/onlydust/onlydust.service.spec.ts
src/onlydust/onlydust.service.ts
src/scorer/scorer.service.ts

refactor: rename the mission count into contribution count metric

---

src/commands/score-contributors.command.spec.ts
src/contributors/contributor.entity.ts
src/contributors/contributors.controller.spec.ts
src/contributors/contributors.service.spec.ts
src/contributors/types/contributor.interface.ts
src/metrics/index.ts
src/scorer/scorer.service.spec.ts
src/scorer/scorer.service.ts
src/synchronization/synchronization.service.ts

feat: setup 3 scorings

---

src/contributors/contributor.entity.ts
src/contributors/contributors.controller.spec.ts
src/contributors/contributors.service.spec.ts
src/contributors/types/contributor.interface.ts
src/scorer/scorer.service.spec.ts
src/scorer/scorer.service.ts
src/synchronization/synchronization.service.ts

feat: add a maxRank property

---

src/commands/onlydust-import.command.spec.ts
src/commands/onlydust-import.command.ts
src/commands/synchronize-contributor.command.spec.ts
src/commands/synchronize-contributor.command.ts
src/main-cli.ts
src/metrics/metrics.service.ts
src/synchronization/synchronization.service.ts

refactor: add logging

---

src/github/queries/github-response.example.json
src/github/queries/user-info/user-info.query.ts

fix: get user id instead of nodeid from github
